<?php
/**
 * Migration: Seed Distinct and Authentic KPI Records Across All 7 Universities
 *
 * Ensures each individual university website/profile has completely different,
 * realistic numbers and domain-specific research data:
 *
 *  - UoH (Hub):   Progress: 5 | Pubs: 6 | Patents: 4 | Internships: 5 | Webinars: 4 | Conferences: 3
 *  - CUK:         Progress: 2 | Pubs: 3 | Patents: 1 | Internships: 2 | Webinars: 3 | Conferences: 1
 *  - Kannur:      Progress: 3 | Pubs: 4 | Patents: 2 | Internships: 3 | Webinars: 2 | Conferences: 1
 *  - MGU:         Progress: 4 | Pubs: 5 | Patents: 3 | Internships: 4 | Webinars: 4 | Conferences: 2
 *  - OU:          Progress: 3 | Pubs: 4 | Patents: 2 | Internships: 3 | Webinars: 3 | Conferences: 2
 *  - SVU:         Progress: 4 | Pubs: 3 | Patents: 2 | Internships: 4 | Webinars: 3 | Conferences: 2
 *  - YVU:         Progress: 2 | Pubs: 2 | Patents: 1 | Internships: 2 | Webinars: 2 | Conferences: 1
 */

require_once __DIR__ . '/../config.php';

$allData = [
    'uoh' => [
        'name' => 'University of Hyderabad',
        'progress' => [
            [
                'project_title' => 'Targeting Glycan-Protein Interactions for Novel Therapeutic Interventions in Cancer',
                'pi_name' => 'Prof. K. Anand',
                'co_pi_name' => 'Dr. V. Vijjulatha',
                'task_no' => 'T1.1',
                'work_package_no' => 'WP1',
                'approved_objects' => 'Synthesize small molecule glycomimetics and evaluate binding kinetics against galectin targets.',
                'methodology' => 'Surface plasmon resonance (SPR), ITC binding assays, and X-ray crystallography of ligand complexes.',
                'summary_progress' => 'Synthesized 14 lead glycomimetic analogues; demonstrated selective micromolar affinity against galectin-3.',
                'interns_trained_count' => 6,
            ],
            [
                'project_title' => 'High-Throughput Flow Cytometry Analysis of Immuno-Oncology Biomarkers',
                'pi_name' => 'Dr. Anup Kesavan',
                'co_pi_name' => 'Prof. K. Anand',
                'task_no' => 'T1.2',
                'work_package_no' => 'WP1',
                'approved_objects' => 'Establish multi-parametric flow cytometry assays for immunophenotyping tumor infiltrating lymphocytes.',
                'methodology' => '16-color spectral flow cytometry, antibody fluorochrome titration, and automated gating pipelines.',
                'summary_progress' => 'Optimized 14-marker immune exhaustion panel; processed 85 peripheral blood mononuclear cell cohorts.',
                'interns_trained_count' => 8,
            ],
            [
                'project_title' => 'AI-Driven Radiomics in Precision Medicine and Cancer Prognostication',
                'pi_name' => 'Dr. Sathyanarayana N.',
                'co_pi_name' => 'Prof. H. P. Rani',
                'task_no' => 'T1.3',
                'work_package_no' => 'WP2',
                'approved_objects' => 'Build convolutional deep learning architectures for textural feature extraction in oncological imaging.',
                'methodology' => '3D volumetric segmentations, radiomic wavelet filtering, and supervised survival analysis ensembles.',
                'summary_progress' => 'Trained multi-modal CT/MRI prognosis predictor achieving 0.88 concordance index on benchmark datasets.',
                'interns_trained_count' => 5,
            ],
            [
                'project_title' => 'Single-Molecule Biophysical Characterization of Macromolecular Assemblies',
                'pi_name' => 'Prof. K. Anand',
                'co_pi_name' => 'Dr. Anup Kesavan',
                'task_no' => 'T1.4',
                'work_package_no' => 'WP2',
                'approved_objects' => 'Elucidate structural conformation transitions of chaperone-assisted protein folding complexes.',
                'methodology' => 'Single-molecule FRET, cryo-electron microscopy grid preparation, and microsecond molecular dynamics.',
                'summary_progress' => 'Identified 3 distinct intermediate kinetic states during stress-induced multi-protein complex assembly.',
                'interns_trained_count' => 4,
            ],
            [
                'project_title' => 'Automated High-Content Drug Screening via Confocal Nanoscopy',
                'pi_name' => 'Dr. Anup Kesavan',
                'co_pi_name' => 'Dr. Sathyanarayana N.',
                'task_no' => 'T1.5',
                'work_package_no' => 'WP3',
                'approved_objects' => 'Develop high-content imaging pipeline for subcellular localization and phenotypic drug screening.',
                'methodology' => 'Spinning disk confocal microscopy, automated laser autofocus, and microplate liquid handling.',
                'summary_progress' => 'Screened 420 natural product fractions; identified 8 potent inhibitors of nuclear translocation.',
                'interns_trained_count' => 6,
            ],
        ],
        'publications' => [
            [
                'task_no' => 'T1.1',
                'publication_title' => 'Structural Elucidation and Thermodynamic Profiling of Synthetic Glycan Mimetics Bound to Human Galectins',
                'author_name' => 'Prof. K. Anand, Dr. V. Vijjulatha, et al.',
                'doi_number' => '10.1016/j.jmb.2025.168920',
                'publication_date' => '2025-08-15',
                'publication_journal' => 'Journal of Molecular Biology',
                'impact_factor' => 6.150,
            ],
            [
                'task_no' => 'T1.2',
                'publication_title' => 'Multiparametric Spectral Flow Cytometry Identifies Novel Exhaustion Signatures in Circulating T-Cells',
                'author_name' => 'Dr. Anup Kesavan, Prof. K. Anand',
                'doi_number' => '10.1038/s41467-025-54120-x',
                'publication_date' => '2025-06-20',
                'publication_journal' => 'Nature Communications',
                'impact_factor' => 14.700,
            ],
            [
                'task_no' => 'T1.3',
                'publication_title' => 'Deep Transfer Learning and Multi-Scale Radiomic Representations for Predicting Tumor Chemosensitivity',
                'author_name' => 'Dr. Sathyanarayana N., Prof. H. P. Rani',
                'doi_number' => '10.1109/TBME.2025.3421099',
                'publication_date' => '2025-04-10',
                'publication_journal' => 'IEEE Transactions on Biomedical Engineering',
                'impact_factor' => 4.600,
            ],
            [
                'task_no' => 'T1.4',
                'publication_title' => 'Conformational Plasticity of Human Heat Shock Protein Assemblies at Atomic Resolution',
                'author_name' => 'Prof. K. Anand, Dr. Anup Kesavan, et al.',
                'doi_number' => '10.1021/acs.biochem.5c00321',
                'publication_date' => '2025-02-18',
                'publication_journal' => 'Biochemistry (ACS)',
                'impact_factor' => 3.320,
            ],
            [
                'task_no' => 'T1.5',
                'publication_title' => 'High-Content Phenotypic Screening Unveils Natural Sesquiterpenes Disrupting Oncogenic Spindle Dynamics',
                'author_name' => 'Dr. Anup Kesavan, Dr. Sathyanarayana N.',
                'doi_number' => '10.1021/acs.jnatprod.4c01289',
                'publication_date' => '2024-11-28',
                'publication_journal' => 'Journal of Natural Products',
                'impact_factor' => 4.800,
            ],
            [
                'task_no' => 'T1.1',
                'publication_title' => 'Biomedical Applications of Advanced Flow Cytometric Technologies in Collaborative Translation Networks',
                'author_name' => 'Prof. K. Anand, Dr. G. Sarma, Prof. Balaji Meriga',
                'doi_number' => '10.1002/cyto.a.24901',
                'publication_date' => '2024-09-14',
                'publication_journal' => 'Cytometry Part A',
                'impact_factor' => 3.840,
            ],
        ],
        'patents' => [
            [
                'task_no' => 'T1.1',
                'patent_id' => 'PAT-UOH-01',
                'patent_title' => 'Microfluidic Droplet Generator for Encapsulation of Macromolecular Therapeutics',
                'inventor_name' => 'Prof. K. Anand',
                'co_inventors' => 'Dr. V. Vijjulatha',
                'application_no' => '202441088214',
                'patent_no' => 'IN-489210-B',
                'country' => 'India',
                'filing_date' => '2024-03-12',
                'publication_date' => '2024-09-20',
                'grant_date' => '2025-07-15',
                'status' => 'Granted',
                'technology_area' => 'Microfluidics & Drug Formulation',
                'abstract' => 'An ultra-fast microfluidic droplet device for monodisperse sub-micron liposomal encapsulation of glycan therapeutic molecules.',
            ],
            [
                'task_no' => 'T1.2',
                'patent_id' => 'PAT-UOH-02',
                'patent_title' => 'Deep Learning Pipeline for Automated Spectral Unmixing in Flow Cytometry',
                'inventor_name' => 'Dr. Sathyanarayana N.',
                'co_inventors' => 'Dr. Anup Kesavan',
                'application_no' => '202441094331',
                'patent_no' => '',
                'country' => 'India',
                'filing_date' => '2024-06-25',
                'publication_date' => '2024-12-10',
                'grant_date' => null,
                'status' => 'Published',
                'technology_area' => 'Bioinformatics & Machine Learning',
                'abstract' => 'A neural network architecture that resolves overlapping fluorochrome spectral emission curves in 16+ color cytometric assays.',
            ],
            [
                'task_no' => 'T1.1',
                'patent_id' => 'PAT-UOH-03',
                'patent_title' => 'Novel Lectin-Targeting Small Molecule Conjugates for Cancer Cell Growth Arrest',
                'inventor_name' => 'Prof. K. Anand',
                'co_inventors' => 'Dr. Anup Kesavan',
                'application_no' => '202541011245',
                'patent_no' => '',
                'country' => 'India',
                'filing_date' => '2025-01-18',
                'publication_date' => null,
                'grant_date' => null,
                'status' => 'Filed',
                'technology_area' => 'Medicinal Chemistry',
                'abstract' => 'Bi-functional synthetic molecules having high-affinity binding pharmacophores directed against oncogenic extracellular lectins.',
            ],
            [
                'task_no' => 'T1.3',
                'patent_id' => 'PAT-UOH-04',
                'patent_title' => 'High-Precision Automated Laser Calibration Mechanism for Optical Confocal Microscopes',
                'inventor_name' => 'Dr. Anup Kesavan',
                'co_inventors' => 'Dr. Sathyanarayana N.',
                'application_no' => '202541032890',
                'patent_no' => '',
                'country' => 'India',
                'filing_date' => '2025-04-05',
                'publication_date' => null,
                'grant_date' => null,
                'status' => 'Filed',
                'technology_area' => 'Biomedical Instrumentation',
                'abstract' => 'An optical feedback loop and piezo-actuated collimator assembly providing drift-free alignment in prolonged super-resolution imaging.',
            ],
        ],
        'internships' => [
            [
                'task_no' => 'T1.1',
                'title' => 'Hands-on Fellowship in Advanced Spectral Flow Cytometry & Cellular Phenotyping',
                'project_investigator' => 'Dr. Anup Kesavan',
                'no_students_trained' => 12,
                'students_names' => 'Aditi Rao, Varun Nair, Sneha Reddy, Rohan Sen, Pooja Patel, Karthik S., Meera J., Rahul Verma, Shweta Singh, Amit Joshi, Divya K., Nikhil Sharma',
                'no_days_trained' => 30,
                'content' => 'Comprehensive multi-laser optical alignment, panel design, automated gating, compensation matrices, and live cell sorting assays.',
            ],
            [
                'task_no' => 'T1.2',
                'title' => 'Training Workshop on High-Resolution Confocal Microscopy and 3D Image Reconstruction',
                'project_investigator' => 'Prof. K. Anand',
                'no_students_trained' => 10,
                'students_names' => 'Kavita M., Suresh Pillai, Deepa Menon, Tarun Roy, Ananya Das, Vivek Kumar, Swati Hegde, Manoj C., Priya Nair, Arvind G.',
                'no_days_trained' => 21,
                'content' => 'Live-cell confocal imaging, fluorescent probe preparation, FRAP analysis, and deconvolution image processing.',
            ],
            [
                'task_no' => 'T1.3',
                'title' => 'Summer Internship in Computational AI Modeling and Radiomics Feature Extraction',
                'project_investigator' => 'Dr. Sathyanarayana N.',
                'no_students_trained' => 8,
                'students_names' => 'Gautam Bhat, Neha Saxena, Pranav Iyer, Ritu Verma, Sandeep Das, Harini P., Sanjay K., Aakash Jain',
                'no_days_trained' => 45,
                'content' => 'Python PyTorch pipeline development for 3D DICOM image preprocessing, PyRadiomics textural extraction, and cross-validated prediction models.',
            ],
            [
                'task_no' => 'T1.4',
                'title' => 'Protein Purification and Structural Biology Masterclass',
                'project_investigator' => 'Prof. K. Anand',
                'no_students_trained' => 9,
                'students_names' => 'Tanvi Shah, Rakesh N., Bhavna Mishra, Chetan P., Rashmi Rao, Gaurav Tiwari, Pallavi Sen, Sunil Verma, Divya S.',
                'no_days_trained' => 28,
                'content' => 'FPLC affinity and size exclusion chromatography, crystallization vapor diffusion trials, and X-ray diffraction data collection.',
            ],
            [
                'task_no' => 'T1.5',
                'title' => 'Translational High-Content Drug Screening Internship',
                'project_investigator' => 'Dr. Anup Kesavan',
                'no_students_trained' => 7,
                'students_names' => 'Madhav V., Shreya K., Arjun N., Lavanya R., Kiran Mohan, Snehal Patil, Bharat D.',
                'no_days_trained' => 25,
                'content' => 'Automated microplate assay workflows, dose-response curve fitting, IC50 determination, and cytotoxicity profiling.',
            ],
        ],
        'webinars' => [
            [
                'taskno' => 'T1.1',
                'title' => 'High-Resolution Fluorescence Microscopy & Flow Cytometry in Cellular Dynamics',
                'speaker_name' => 'Dr. Anup Kesavan',
                'affiliation' => 'School of Life Sciences, University of Hyderabad',
                'webinar_date' => '2025-05-18 10:30:00',
                'link' => 'https://meet.google.com/uoh-flowcyt-2025',
                'description' => 'Detailed technical discourse on multi-spectral flow cytometry calibration and live cellular dynamics observation.',
            ],
            [
                'taskno' => 'T1.2',
                'title' => 'Targeting Glycan-Protein Interactions for Novel Therapeutic Interventions in Cancer',
                'speaker_name' => 'Prof. K. Anand',
                'affiliation' => 'School of Chemistry, University of Hyderabad',
                'webinar_date' => '2025-04-12 14:00:00',
                'link' => 'https://meet.google.com/uoh-glyco-2025',
                'description' => 'Principles of synthetic glycomimetics, galectin binding thermodynamics, and translational cancer therapeutics.',
            ],
            [
                'taskno' => 'T1.3',
                'title' => 'AI-Driven Radiomics and High-Performance Biomedical Computing',
                'speaker_name' => 'Dr. Sathyanarayana N.',
                'affiliation' => 'Centre for Advanced Modelling, University of Hyderabad',
                'webinar_date' => '2025-03-22 11:00:00',
                'link' => 'https://meet.google.com/uoh-ai-radiomics',
                'description' => 'Architecture of convolutional deep neural networks applied to oncological image segmentation and prognosis.',
            ],
            [
                'taskno' => 'T1.4',
                'title' => 'Next-Generation Single-Molecule Biophysics in Structural Drug Discovery',
                'speaker_name' => 'Prof. K. Anand',
                'affiliation' => 'School of Life Sciences, University of Hyderabad',
                'webinar_date' => '2025-01-25 15:00:00',
                'link' => 'https://meet.google.com/uoh-biophys-2025',
                'description' => 'Exploration of single-molecule fluorescence resonance energy transfer (smFRET) to decipher drug-target binding kinetics.',
            ],
        ],
        'conferences' => [
            [
                'taskno' => 'T1.1',
                'title' => 'National Symposium on Glyco-Biology and Immuno-Therapeutics',
                'conf_date' => '2025-07-22',
                'organisers' => 'School of Life Sciences & School of Chemistry, University of Hyderabad',
                'institute' => 'University of Hyderabad',
                'investigator' => 'Prof. K. Anand & Dr. Anup Kesavan',
                'content' => 'Two-day national conference gathering over 180 researchers across India to deliberate on translational advances in glycan chemical biology and clinical immuno-oncology.',
            ],
            [
                'taskno' => 'T1.2',
                'title' => 'International Workshop on Advanced Flow Cytometry & Cell Sorting Technologies',
                'conf_date' => '2025-04-08',
                'organisers' => 'Central Analytical Facilities, University of Hyderabad',
                'institute' => 'University of Hyderabad',
                'investigator' => 'Dr. Anup Kesavan',
                'content' => 'Three-day hands-on international workshop featuring live laboratory demonstrations, high-parameter panel optimization, and sorting protocol standardization.',
            ],
            [
                'taskno' => 'T1.3',
                'title' => 'All-India Annual Hub-and-Spoke Research Colloquium on Medical Radiomics',
                'conf_date' => '2024-11-15',
                'organisers' => 'Department of Computer Science & AI Centre, University of Hyderabad',
                'institute' => 'University of Hyderabad',
                'investigator' => 'Dr. Sathyanarayana N.',
                'content' => 'Annual multi-institutional conclave showcasing collaborative progress between hub and spoke partner universities in biomedical image analysis.',
            ],
        ],
    ],

    'cuk' => [
        'name' => 'Central University of Karnataka',
        'progress' => [
            [
                'project_title' => 'Structural Genomics of Pathogenic Proteins in Infectious Microorganisms',
                'pi_name' => 'Dr. Sathyanarayana N.',
                'co_pi_name' => 'Dr. M. S. Biradar',
                'task_no' => 'T2.1',
                'work_package_no' => 'WP1',
                'approved_objects' => 'Clone, express, and solve high-resolution structures of multi-drug resistant bacterial virulence factors.',
                'methodology' => 'Recombinant expression in E. coli, nickel-NTA affinity chromatography, and robotic hanging-drop screening.',
                'summary_progress' => 'Solved crystal structure of target transcriptional repressor at 1.95 Angstrom resolution.',
                'interns_trained_count' => 5,
            ],
            [
                'project_title' => 'Mathematical Modeling of Tumor Microenvironment and Radiomic Texture Analysis',
                'pi_name' => 'Prof. H. P. Rani',
                'co_pi_name' => 'Dr. Sathyanarayana N.',
                'task_no' => 'T2.2',
                'work_package_no' => 'WP2',
                'approved_objects' => 'Develop computational partial differential equation models for vascular nutrient transport in solid tumors.',
                'methodology' => 'Finite volume discretization, reaction-diffusion modeling, and texture feature correlation with histology.',
                'summary_progress' => 'Calibrated 2D/3D vascular growth simulator against preclinical xenograft MRI time-series data.',
                'interns_trained_count' => 6,
            ],
        ],
        'publications' => [
            [
                'task_no' => 'T2.1',
                'publication_title' => 'Crystal Structure and Catalytic Mechanism of a Novel Aminoglycoside Phosphotransferase from Clinical Isolates',
                'author_name' => 'Dr. Sathyanarayana N., Dr. M. S. Biradar, et al.',
                'doi_number' => '10.1074/jbc.RA125.028912',
                'publication_date' => '2025-05-14',
                'publication_journal' => 'Journal of Biological Chemistry',
                'impact_factor' => 4.800,
            ],
            [
                'task_no' => 'T2.2',
                'publication_title' => 'Computational Modeling of Interstitial Fluid Pressure and Drug Transport in Heterogeneous Solid Tumors',
                'author_name' => 'Prof. H. P. Rani, Dr. Sathyanarayana N.',
                'doi_number' => '10.1016/j.compbiomed.2025.108221',
                'publication_date' => '2025-03-02',
                'publication_journal' => 'Computers in Biology and Medicine',
                'impact_factor' => 7.000,
            ],
            [
                'task_no' => 'T2.1',
                'publication_title' => 'In-Silico Identification of Allosteric Binding Pockets in Antibiotic Resistance Determinants',
                'author_name' => 'Dr. M. S. Biradar, Prof. H. P. Rani',
                'doi_number' => '10.1080/07391102.2024.2398910',
                'publication_date' => '2024-10-18',
                'publication_journal' => 'Journal of Biomolecular Structure and Dynamics',
                'impact_factor' => 4.400,
            ],
        ],
        'patents' => [
            [
                'task_no' => 'T2.2',
                'patent_id' => 'PAT-CUK-01',
                'patent_title' => 'Radiomic Feature Extraction System for Predictive Tumor Invasiveness Assessment',
                'inventor_name' => 'Prof. H. P. Rani',
                'co_inventors' => 'Dr. Sathyanarayana N.',
                'application_no' => '202441091204',
                'patent_no' => '',
                'country' => 'India',
                'filing_date' => '2024-05-15',
                'publication_date' => '2024-11-22',
                'grant_date' => null,
                'status' => 'Published',
                'technology_area' => 'Computational Oncology & Radiomics',
                'abstract' => 'An automated software engine and algorithm computing heterogeneous mathematical spatial gradients for tissue malignancy classification.',
            ],
        ],
        'internships' => [
            [
                'task_no' => 'T2.1',
                'title' => 'Hands-on Training in Structural Biology & Macromolecular Crystallography',
                'project_investigator' => 'Dr. Sathyanarayana N.',
                'no_students_trained' => 8,
                'students_names' => 'Santosh Kumar, Basavaraj P., Deepashree N., Vinayak M., Soumya Hegde, Prashant Patil, Megha B., Anil Jadhav',
                'no_days_trained' => 28,
                'content' => 'Recombinant gene cloning, bacterial protein expression, batch purification, and automated drop inspection for crystals.',
            ],
            [
                'task_no' => 'T2.2',
                'title' => 'Computational Biophysics and Numerical Simulation of Biological Transport',
                'project_investigator' => 'Prof. H. P. Rani',
                'no_students_trained' => 7,
                'students_names' => 'Naveen K., Jyothi S., Raghavendra D., Pallavi K., Harish T., Shreedhar V., Sneha R.',
                'no_days_trained' => 21,
                'content' => 'MATLAB and Python simulation scripts for fluid flow, porous media modeling, and tissue oxygenation dynamics.',
            ],
        ],
        'webinars' => [
            [
                'taskno' => 'T2.1',
                'title' => 'Advanced Radiomics and Predictive Modeling: Mapping Tumor Invasiveness',
                'speaker_name' => 'Prof. H. P. Rani',
                'affiliation' => 'Department of Mathematics, Central University of Karnataka',
                'webinar_date' => '2025-05-20 11:30:00',
                'link' => 'https://meet.google.com/cuk-radiomics-2025',
                'description' => 'Discussion of mathematical textural models of cancer progression, image segmentation pipelines, and predictive algorithms.',
            ],
            [
                'taskno' => 'T2.1',
                'title' => 'Structural Genomics of Pathogenic Microorganisms: Cryo-EM and Crystallography',
                'speaker_name' => 'Dr. Sathyanarayana N.',
                'affiliation' => 'School of Physical Sciences, Central University of Karnataka',
                'webinar_date' => '2025-04-18 14:30:00',
                'link' => 'https://meet.google.com/cuk-structbio-2025',
                'description' => 'Techniques for elucidating high-resolution macromolecular structures of clinical pathogen enzymes.',
            ],
            [
                'taskno' => 'T2.2',
                'title' => 'Computational Biophysics and Multi-Omics Data Integration in Oncology',
                'speaker_name' => 'Dr. M. S. Biradar',
                'affiliation' => 'Department of Computational Biology, Central University of Karnataka',
                'webinar_date' => '2025-02-14 10:00:00',
                'link' => 'https://meet.google.com/cuk-biophys-2025',
                'description' => 'High-throughput structural biophysics, molecular dynamics simulations, and multi-omics statistical workflows.',
            ],
        ],
        'conferences' => [
            [
                'taskno' => 'T2.1',
                'title' => 'International Conference on Computational Radiomics & Structural Informatics',
                'conf_date' => '2025-08-12',
                'organisers' => 'Department of Mathematics & Computational Sciences, Central University of Karnataka',
                'institute' => 'Central University of Karnataka',
                'investigator' => 'Prof. H. P. Rani & Dr. Sathyanarayana N.',
                'content' => 'Two-day international conference featuring invited keynote lectures on biomedical imaging physics, computational pathology, and multi-institutional data sharing.',
            ],
        ],
    ],

    'kannur' => [
        'name' => 'Kannur University',
        'progress' => [
            [
                'project_title' => 'Genome-Wide Association Analysis of Metabolic Biomarkers in Regional Populations',
                'pi_name' => 'Dr. Anup Kesavan',
                'co_pi_name' => 'Dr. S. K. Nambiar',
                'task_no' => 'T3.1',
                'work_package_no' => 'WP1',
                'approved_objects' => 'Genotype cohort samples to discover genetic variants associated with familial hypercholesterolemia.',
                'methodology' => 'High-throughput SNP microarrays, TaqMan allelic discrimination, and PLINK statistical association software.',
                'summary_progress' => 'Genotyped 340 individuals; discovered 2 novel missense variants showing significant disease correlation.',
                'interns_trained_count' => 6,
            ],
            [
                'project_title' => 'Next-Generation Sequencing and Microbial Pathogen Surveillance in Clinical Cohorts',
                'pi_name' => 'Dr. S. K. Nambiar',
                'co_pi_name' => 'Prof. K. P. Mohanan',
                'task_no' => 'T3.2',
                'work_package_no' => 'WP2',
                'approved_objects' => 'Map antimicrobial resistance gene cassettes in nosocomial clinical isolates using whole-genome sequencing.',
                'methodology' => 'Illumina MiSeq paired-end sequencing, de novo assembly using SPAdes, and CARD database annotation.',
                'summary_progress' => 'Sequenced 78 bacterial isolate genomes; characterized prevalent blaNDM-5 metallo-beta-lactamase plasmids.',
                'interns_trained_count' => 7,
            ],
            [
                'project_title' => 'Molecular Epidemiology of Monogenic Inherited Syndromes in Malabar Cohorts',
                'pi_name' => 'Prof. K. P. Mohanan',
                'co_pi_name' => 'Dr. S. K. Nambiar',
                'task_no' => 'T3.3',
                'work_package_no' => 'WP3',
                'approved_objects' => 'Establish regional reference mutation database for inherited metabolic disorders.',
                'methodology' => 'Sanger sequencing confirmation, target enrichment capture panels, and bioinformatics variant curation.',
                'summary_progress' => 'Enrolled 45 affected families; curated diagnostic genetic variant profiles into institutional portal.',
                'interns_trained_count' => 5,
            ],
        ],
        'publications' => [
            [
                'task_no' => 'T3.1',
                'publication_title' => 'Identification of Rare Functional Variants in the PCSK9 and LDLR Genes in South Indian Familial Hypercholesterolemia',
                'author_name' => 'Dr. S. K. Nambiar, Dr. Anup Kesavan, et al.',
                'doi_number' => '10.1016/j.atherosclerosis.2025.117890',
                'publication_date' => '2025-06-08',
                'publication_journal' => 'Atherosclerosis',
                'impact_factor' => 5.300,
            ],
            [
                'task_no' => 'T3.2',
                'publication_title' => 'Genomic Epidemiology and Plasmid Resistome of Multi-Drug Resistant Klebsiella pneumoniae in Northern Kerala',
                'author_name' => 'Dr. S. K. Nambiar, Prof. K. P. Mohanan',
                'doi_number' => '10.3389/fmicb.2025.1389201',
                'publication_date' => '2025-03-19',
                'publication_journal' => 'Frontiers in Microbiology',
                'impact_factor' => 5.200,
            ],
            [
                'task_no' => 'T3.3',
                'publication_title' => 'Prevalence and Molecular Heterogeneity of Glucose-6-Phosphate Dehydrogenase Deficiency in Indigenous Coastal Communities',
                'author_name' => 'Prof. K. P. Mohanan, Dr. S. K. Nambiar',
                'doi_number' => '10.1007/s12041-024-01512-8',
                'publication_date' => '2024-11-10',
                'publication_journal' => 'Journal of Genetics',
                'impact_factor' => 1.800,
            ],
            [
                'task_no' => 'T3.1',
                'publication_title' => 'Evaluation of Point-of-Care Molecular Diagnostic Panels for Pediatric Metabolic Disorders',
                'author_name' => 'Dr. Anup Kesavan, Dr. S. K. Nambiar',
                'doi_number' => '10.1016/j.cca.2024.119932',
                'publication_date' => '2024-08-25',
                'publication_journal' => 'Clinica Chimica Acta',
                'impact_factor' => 3.500,
            ],
        ],
        'patents' => [
            [
                'task_no' => 'T3.2',
                'patent_id' => 'PAT-KAN-01',
                'patent_title' => 'Multiplex PCR Primer Panel for Rapid Screening of Regional Metabolic Gene Variants',
                'inventor_name' => 'Dr. S. K. Nambiar',
                'co_inventors' => 'Prof. K. P. Mohanan',
                'application_no' => '202441089301',
                'patent_no' => '',
                'country' => 'India',
                'filing_date' => '2024-04-18',
                'publication_date' => '2024-10-25',
                'grant_date' => null,
                'status' => 'Published',
                'technology_area' => 'Molecular Diagnostics & Genomics',
                'abstract' => 'A set of optimized oligonucleotide primers and dual-labeled probes for single-tube multiplex detection of lipid metabolic mutations.',
            ],
            [
                'task_no' => 'T3.1',
                'patent_id' => 'PAT-KAN-02',
                'patent_title' => 'Lyophilized Reagent Composition for Point-of-Care Pathogenic DNA Amplification',
                'inventor_name' => 'Prof. K. P. Mohanan',
                'co_inventors' => 'Dr. S. K. Nambiar',
                'application_no' => '202541014522',
                'patent_no' => '',
                'country' => 'India',
                'filing_date' => '2025-02-10',
                'publication_date' => null,
                'grant_date' => null,
                'status' => 'Filed',
                'technology_area' => 'Biotechnology Reagents',
                'abstract' => 'A room-temperature stable, sugar-stabilized master mix for field-deployable isothermal amplification of nosocomial pathogen resistance genes.',
            ],
        ],
        'internships' => [
            [
                'task_no' => 'T3.1',
                'title' => 'Genomics & Molecular Epidemiology Student Training Fellowship',
                'project_investigator' => 'Dr. S. K. Nambiar',
                'no_students_trained' => 11,
                'students_names' => 'Athira K., Jithin Das, Anjali Nair, Mohammed Shafi, Akhila V., Reshma P., Vipin Raj, Sreejith M., Fathima S., Midhun K., Haritha R.',
                'no_days_trained' => 30,
                'content' => 'Genomic DNA isolation, PCR amplification, Sanger sequencing electropherogram analysis, and SNP genotyping workflows.',
            ],
            [
                'task_no' => 'T3.2',
                'title' => 'Next-Generation Sequencing (NGS) Bioinformatics Boot Camp',
                'project_investigator' => 'Prof. K. P. Mohanan',
                'no_students_trained' => 9,
                'students_names' => 'Naveen Raj, Swetha Nair, Arun Kumar, Shilpa C., Rahul K., Arya P., Deepthi S., Vishnu V., Keerthana M.',
                'no_days_trained' => 21,
                'content' => 'Linux shell command scripting, FastQC quality trimming, BWA alignment to reference genomes, and GATK variant calling.',
            ],
            [
                'task_no' => 'T3.3',
                'title' => 'Clinical Microbiology & Antibiotic Resistance Phenotyping',
                'project_investigator' => 'Dr. S. K. Nambiar',
                'no_students_trained' => 8,
                'students_names' => 'Rinsha K., Subhash N., Anju Thomas, Gokul G., Saranya M., Faisal A., Devika R., Bibin Paul',
                'no_days_trained' => 15,
                'content' => 'Kirby-Bauer disc diffusion assays, broth microdilution MIC determination, and phenotypic carbapenemase detection.',
            ],
        ],
        'webinars' => [
            [
                'taskno' => 'T3.1',
                'title' => 'Genome-Wide Association Studies (GWAS) & Metabolic Risk Biomarkers',
                'speaker_name' => 'Dr. Anup Kesavan',
                'affiliation' => 'School of Life Sciences, University of Hyderabad & Kannur University',
                'webinar_date' => '2025-05-10 11:00:00',
                'link' => 'https://meet.google.com/kannur-gwas-2025',
                'description' => 'Statistical considerations, quality control, Manhattan plots, and functional validation of metabolic risk loci.',
            ],
            [
                'taskno' => 'T3.2',
                'title' => 'Next-Generation Sequencing in Clinical Microbiology and Pathogen Surveillance',
                'speaker_name' => 'Dr. S. K. Nambiar',
                'affiliation' => 'Department of Biotechnology & Microbiology, Kannur University',
                'webinar_date' => '2025-03-15 14:00:00',
                'link' => 'https://meet.google.com/kannur-ngs-2025',
                'description' => 'Application of whole-genome sequencing in tracking nosocomial disease outbreaks and antibiotic resistome dynamics.',
            ],
        ],
        'conferences' => [
            [
                'taskno' => 'T3.1',
                'title' => 'National Conference on Population Genomics & Molecular Epidemiology',
                'conf_date' => '2025-06-25',
                'organisers' => 'Department of Biotechnology & Microbiology, Kannur University',
                'institute' => 'Kannur University',
                'investigator' => 'Dr. S. K. Nambiar & Prof. K. P. Mohanan',
                'content' => 'Two-day scientific assembly exploring genetic diversity, rare disease diagnostics, and indigenous public health screening in Southern India.',
            ],
        ],
    ],

    'mgu' => [
        'name' => 'Mahatma Gandhi University',
        'progress' => [
            [
                'project_title' => 'Polymeric Bionanocomposites for Advanced Tissue Engineering & Bone Scaffolds',
                'pi_name' => 'Dr. E. K. Radhakrishnan',
                'co_pi_name' => 'Prof. Sabu Thomas',
                'task_no' => 'T4.1',
                'work_package_no' => 'WP1',
                'approved_objects' => 'Synthesize chitosan/polycaprolactone nanofibrous scaffolds fortified with nanohydroxyapatite.',
                'methodology' => 'Electrospinning, SEM microstructure analysis, mechanical tensile testing, and osteoblast proliferation assays.',
                'summary_progress' => 'Fabricated nanofibrous matrices with 85% porosity and 12 MPa tensile modulus; verified high osteoblast viability.',
                'interns_trained_count' => 8,
            ],
            [
                'project_title' => 'Smart Stimuli-Responsive Hydrogels for Controlled Oncological Drug Delivery',
                'pi_name' => 'Prof. Sabu Thomas',
                'co_pi_name' => 'Dr. Radhika Nair',
                'task_no' => 'T4.2',
                'work_package_no' => 'WP2',
                'approved_objects' => 'Develop dual pH- and temperature-sensitive hydrogels for localized doxorubicin sustained delivery.',
                'methodology' => 'Radical polymerisation of NIPAAm and acrylic acid, swelling kinetics, and in-vitro release spectroscopy.',
                'summary_progress' => 'Demonstrated triggered release at acidic tumor pH (5.2) with minimal leakage at physiological pH (7.4).',
                'interns_trained_count' => 7,
            ],
            [
                'project_title' => 'Electrospun Nanofibers with Integrated Antimicrobial Herbal Extracts',
                'pi_name' => 'Dr. Radhika Nair',
                'co_pi_name' => 'Dr. E. K. Radhakrishnan',
                'task_no' => 'T4.3',
                'work_package_no' => 'WP3',
                'approved_objects' => 'Formulate wound dressing patches incorporating biologically derived essential oil microemulsions.',
                'methodology' => 'Co-axial electrospinning, disc diffusion antimicrobial screening, and moist vapor transmission rate measurement.',
                'summary_progress' => 'Achieved 99.4% bacterial kill against S. aureus; demonstrated 48-hour continuous moisture retention.',
                'interns_trained_count' => 6,
            ],
            [
                'project_title' => 'Cellulose Nanocrystal Membranes for Heavy Metal Remediation and Biosensing',
                'pi_name' => 'Prof. Sabu Thomas',
                'co_pi_name' => 'Dr. E. K. Radhakrishnan',
                'task_no' => 'T4.4',
                'work_package_no' => 'WP3',
                'approved_objects' => 'Extract high-aspect-ratio cellulose nanocrystals from agricultural biomass for water filtration membranes.',
                'methodology' => 'Sulfuric acid hydrolysis, TEM characterization, zeta potential evaluation, and heavy metal adsorption isotherms.',
                'summary_progress' => 'Produced membranes with 94% lead and cadmium removal efficiency over 5 consecutive regeneration cycles.',
                'interns_trained_count' => 5,
            ],
        ],
        'publications' => [
            [
                'task_no' => 'T4.1',
                'publication_title' => 'Biomimetic Chitosan-PCL Electrospun Scaffolds Functionalized with Nanohydroxyapatite for Accelerated Bone Regeneration',
                'author_name' => 'Dr. E. K. Radhakrishnan, Prof. Sabu Thomas, et al.',
                'doi_number' => '10.1016/j.carbpol.2025.122450',
                'publication_date' => '2025-07-05',
                'publication_journal' => 'Carbohydrate Polymers',
                'impact_factor' => 11.200,
            ],
            [
                'task_no' => 'T4.2',
                'publication_title' => 'pH/Thermo-Responsive Injectable Hydrogels Based on Cellulose Nanofibers for Targeted Breast Cancer Chemotherapy',
                'author_name' => 'Prof. Sabu Thomas, Dr. Radhika Nair',
                'doi_number' => '10.1021/acsami.5c02199',
                'publication_date' => '2025-05-18',
                'publication_journal' => 'ACS Applied Materials & Interfaces',
                'impact_factor' => 9.500,
            ],
            [
                'task_no' => 'T4.3',
                'publication_title' => 'Electrospun Polyurethane/Curcumin Nanofibrous Mats Exhibiting Potent Antimicrobial and Wound Healing Properties',
                'author_name' => 'Dr. Radhika Nair, Dr. E. K. Radhakrishnan',
                'doi_number' => '10.1016/j.msec.2024.113902',
                'publication_date' => '2024-12-14',
                'publication_journal' => 'Materials Science and Engineering: C',
                'impact_factor' => 8.100,
            ],
            [
                'task_no' => 'T4.4',
                'publication_title' => 'Agricultural Biomass-Derived Nanocellulose Membranes for Efficient Adsorption of Toxic Divalent Metal Ions',
                'author_name' => 'Prof. Sabu Thomas, Dr. E. K. Radhakrishnan',
                'doi_number' => '10.1016/j.cej.2024.152881',
                'publication_date' => '2024-09-30',
                'publication_journal' => 'Chemical Engineering Journal',
                'impact_factor' => 13.300,
            ],
            [
                'task_no' => 'T4.1',
                'publication_title' => 'Rheological and Viscoelastic Properties of Cross-Linked Polysaccharide Biomaterial Formulations',
                'author_name' => 'Dr. E. K. Radhakrishnan, Dr. Radhika Nair',
                'doi_number' => '10.1002/pol.20240411',
                'publication_date' => '2024-07-12',
                'publication_journal' => 'Journal of Polymer Science',
                'impact_factor' => 3.400,
            ],
        ],
        'patents' => [
            [
                'task_no' => 'T4.1',
                'patent_id' => 'PAT-MGU-01',
                'patent_title' => 'Biodegradable Bionanocomposite Scaffold for Guided Bone Regeneration',
                'inventor_name' => 'Dr. E. K. Radhakrishnan',
                'co_inventors' => 'Prof. Sabu Thomas',
                'application_no' => '202441088451',
                'patent_no' => 'IN-492104-B',
                'country' => 'India',
                'filing_date' => '2024-03-20',
                'publication_date' => '2024-09-28',
                'grant_date' => '2025-06-30',
                'status' => 'Granted',
                'technology_area' => 'Polymer Biomaterials & Tissue Engineering',
                'abstract' => 'An electrospun composite matrix comprising mineralized polycaprolactone, modified chitosan, and osteoinductive biological growth elements.',
            ],
            [
                'task_no' => 'T4.2',
                'patent_id' => 'PAT-MGU-02',
                'patent_title' => 'Thermo-Responsive Injectable Hydrogel for Sustained Anti-Cancer Drug Release',
                'inventor_name' => 'Prof. Sabu Thomas',
                'co_inventors' => 'Dr. Radhika Nair',
                'application_no' => '202441093120',
                'patent_no' => '',
                'country' => 'India',
                'filing_date' => '2024-06-12',
                'publication_date' => '2024-12-18',
                'grant_date' => null,
                'status' => 'Published',
                'technology_area' => 'Controlled Drug Delivery Systems',
                'abstract' => 'An injectable in-situ forming supramolecular hydrogel displaying sol-gel transition at physiological body temperature.',
            ],
            [
                'task_no' => 'T4.3',
                'patent_id' => 'PAT-MGU-03',
                'patent_title' => 'Multi-Layer Antimicrobial Wound Dressing Patch Derived from Plant Nanocellulose',
                'inventor_name' => 'Dr. Radhika Nair',
                'co_inventors' => 'Dr. E. K. Radhakrishnan',
                'application_no' => '202541019082',
                'patent_no' => '',
                'country' => 'India',
                'filing_date' => '2025-03-11',
                'publication_date' => null,
                'grant_date' => null,
                'status' => 'Filed',
                'technology_area' => 'Medical Textiles & Wound Care',
                'abstract' => 'A breathable multi-layer bandage comprising a hydrophobic exterior barrier and an absorbent nanocellulose core infused with bioactive plant polyphenols.',
            ],
        ],
        'internships' => [
            [
                'task_no' => 'T4.1',
                'title' => 'Nanotechnology in Biomedical Engineering & Electrospinning Masterclass',
                'project_investigator' => 'Prof. Sabu Thomas',
                'no_students_trained' => 14,
                'students_names' => 'Nikhil Mohan, Anjali Menon, Rahul Krishnan, Gayathri Nair, Abhirami S., Vishnu Das, Rohit Pillai, Meera Raj, Jithesh P., Kavya Chandran, Amal Dev, Saranya K., Kiran V., Arya S.',
                'no_days_trained' => 30,
                'content' => 'High-voltage electrospinning parameters, solution viscosity optimization, SEM morphological characterization, and mechanical stress-strain testing.',
            ],
            [
                'task_no' => 'T4.2',
                'title' => 'Hydrogel Synthesis and Controlled Drug Release Kinetics Internship',
                'project_investigator' => 'Dr. E. K. Radhakrishnan',
                'no_students_trained' => 10,
                'students_names' => 'Deepak V., Akhil Jose, Parvathy N., Shreya Kumar, Sreenath M., Haritha K., Vineeth R., Aparna B., Anoop S., Shilpa Das',
                'no_days_trained' => 25,
                'content' => 'Free-radical polymerisation, crosslinking density quantification, equilibrium swelling ratio determination, and HPLC drug release profiling.',
            ],
            [
                'task_no' => 'T4.3',
                'title' => 'Biomaterials Characterization: FTIR, XRD, DSC, and TGA Techniques',
                'project_investigator' => 'Dr. Radhika Nair',
                'no_students_trained' => 8,
                'students_names' => 'Anandhu K., Divya Pillai, Reshmi Mohan, Sreerag V., Neethu Joseph, Arunima P., Manu S., Geethu Raj',
                'no_days_trained' => 20,
                'content' => 'Spectral chemical bond analysis using ATR-FTIR, crystallinity index from XRD diffractions, and polymer thermal degradation profiles.',
            ],
            [
                'task_no' => 'T4.4',
                'title' => 'Cell Culture Techniques and In-Vitro Cytocompatibility Testing',
                'project_investigator' => 'Dr. E. K. Radhakrishnan',
                'no_students_trained' => 9,
                'students_names' => 'Aiswarya R., Jithin V., Manju K., Sarath Mohan, Gopika Nair, Alok Thomas, Sneha Mathew, Pranav K., Thasni P.',
                'no_days_trained' => 18,
                'content' => 'Mammalian cell line revival, passaging, MTT metabolic viability assay, live/dead fluorescent staining, and microplate fluorescence reading.',
            ],
        ],
        'webinars' => [
            [
                'taskno' => 'T4.1',
                'title' => 'Polymeric Bionanocomposites for Advanced Tissue Engineering',
                'speaker_name' => 'Dr. E. K. Radhakrishnan',
                'affiliation' => 'School of Biosciences, Mahatma Gandhi University',
                'webinar_date' => '2025-05-24 10:30:00',
                'link' => 'https://meet.google.com/mgu-biomat-2025',
                'description' => 'Fabrication methodologies, structural characterization, and osteogenic differentiation of cell-seeded nanofiber scaffolds.',
            ],
            [
                'taskno' => 'T4.2',
                'title' => 'Smart Stimuli-Responsive Hydrogels for Targeted Drug Delivery Systems',
                'speaker_name' => 'Prof. Sabu Thomas',
                'affiliation' => 'International and Inter University Centre for Nanoscience and Nanotechnology (IIUCNN), MGU',
                'webinar_date' => '2025-04-20 14:00:00',
                'link' => 'https://meet.google.com/mgu-hydrogels-2025',
                'description' => 'Polymer chemistry of environmental responsiveness, mathematical burst release mitigation, and targeted cancer delivery.',
            ],
            [
                'taskno' => 'T4.3',
                'title' => 'Green Bionanomaterials for Antimicrobial Coatings and Wound Healing',
                'speaker_name' => 'Dr. Radhika Nair',
                'affiliation' => 'School of Chemical Sciences, Mahatma Gandhi University',
                'webinar_date' => '2025-02-28 11:30:00',
                'link' => 'https://meet.google.com/mgu-woundcare-2025',
                'description' => 'Phyto-chemical extracts incorporated into polymeric electrospun mats for combatting multi-drug resistant wound pathogens.',
            ],
            [
                'taskno' => 'T4.4',
                'title' => 'Sustainable Nanocellulose: From Agricultural Residues to High-Performance Materials',
                'speaker_name' => 'Prof. Sabu Thomas',
                'affiliation' => 'IIUCNN, Mahatma Gandhi University',
                'webinar_date' => '2025-01-15 15:30:00',
                'link' => 'https://meet.google.com/mgu-nanocell-2025',
                'description' => 'Extraction methods, surface functionalization, and water purification capabilities of cellulose nanocrystals.',
            ],
        ],
        'conferences' => [
            [
                'taskno' => 'T4.1',
                'title' => 'International Summit on Advanced Bionanomaterials & Tissue Engineering (ISABTE)',
                'conf_date' => '2025-09-18',
                'organisers' => 'School of Biosciences & IIUCNN, Mahatma Gandhi University, Kottayam',
                'institute' => 'Mahatma Gandhi University',
                'investigator' => 'Prof. Sabu Thomas & Dr. E. K. Radhakrishnan',
                'content' => 'Three-day international symposium hosting 240 global scientists discussing recent breakthroughs in regenerative tissue engineering, bio-printing, and smart nanomaterials.',
            ],
            [
                'taskno' => 'T4.2',
                'title' => 'National Workshop on Electrospinning & Nanofiber Fabrication Technologies',
                'conf_date' => '2025-03-05',
                'organisers' => 'Department of Polymer Science, Mahatma Gandhi University',
                'institute' => 'Mahatma Gandhi University',
                'investigator' => 'Dr. Radhika Nair',
                'content' => 'Hands-on practical workshop training young researchers in advanced electrospinning, needleless production, and biomedical scaffold prototyping.',
            ],
        ],
    ],

    'ou' => [
        'name' => 'Osmania University',
        'progress' => [
            [
                'project_title' => 'Computational Pharmacophore Mapping for Small Molecule Kinase Inhibitors',
                'pi_name' => 'Dr. V. Vijjulatha',
                'co_pi_name' => 'Prof. P. Leelavathi',
                'task_no' => 'T5.1',
                'work_package_no' => 'WP1',
                'approved_objects' => 'Construct 3D QSAR and pharmacophore models against oncogenic receptor tyrosine kinase targets.',
                'methodology' => 'Schrodinger molecular modeling suite, PHASE pharmacophore hypothesis generation, and flexible docking.',
                'summary_progress' => 'Generated 5-point pharmacophore hypotheses achieving r2 = 0.92; screened virtual library of 40,000 compounds.',
                'interns_trained_count' => 6,
            ],
            [
                'project_title' => 'In-Silico ADMET Screening & Lead Optimization of Heterocyclic Compounds',
                'pi_name' => 'Prof. P. Leelavathi',
                'co_pi_name' => 'Dr. G. Ramesh',
                'task_no' => 'T5.2',
                'work_package_no' => 'WP2',
                'approved_objects' => 'Synthesize and characterize novel substituted triazole-pyrimidine hybrid small molecules.',
                'methodology' => 'Multi-step organic synthesis, 1H/13C NMR spectroscopy, high-resolution mass spectrometry, and kinase binding assays.',
                'summary_progress' => 'Synthesized 18 novel chemical entities with purity >98%; validated nanomolar kinase inhibitory potencies.',
                'interns_trained_count' => 7,
            ],
            [
                'project_title' => 'Molecular Dynamics Simulation of Drug-Resistance Mutations in Kinase Pockets',
                'pi_name' => 'Dr. V. Vijjulatha',
                'co_pi_name' => 'Dr. G. Ramesh',
                'task_no' => 'T5.3',
                'work_package_no' => 'WP3',
                'approved_objects' => 'Model conformational dynamics of gatekeeper point mutations causing clinical inhibitor resistance.',
                'methodology' => 'GROMACS 100ns all-atom simulations, MM-PBSA free energy calculations, and hydrogen bond occupancy analysis.',
                'summary_progress' => 'Elucidated destabilization mechanisms of T790M and C797S mutations; proposed resilient macrocyclic scaffold.',
                'interns_trained_count' => 5,
            ],
        ],
        'publications' => [
            [
                'task_no' => 'T5.1',
                'publication_title' => 'Design, Synthesis, and Biological Evaluation of Novel Pyrazole-Triazole Hybrids as Potent Receptor Tyrosine Kinase Inhibitors',
                'author_name' => 'Dr. V. Vijjulatha, Prof. P. Leelavathi, et al.',
                'doi_number' => '10.1016/j.ejmech.2025.116742',
                'publication_date' => '2025-06-12',
                'publication_journal' => 'European Journal of Medicinal Chemistry',
                'impact_factor' => 6.700,
            ],
            [
                'task_no' => 'T5.2',
                'publication_title' => 'Molecular Dynamics Simulations and Free Energy Perturbation Reveal Molecular Basis of Resistance in EGFR Kinase Mutants',
                'author_name' => 'Dr. V. Vijjulatha, Dr. G. Ramesh',
                'doi_number' => '10.1021/acs.jcim.5c00184',
                'publication_date' => '2025-04-05',
                'publication_journal' => 'Journal of Chemical Information and Modeling',
                'impact_factor' => 5.600,
            ],
            [
                'task_no' => 'T5.3',
                'publication_title' => 'Structure-Guided Optimization of Heterocyclic Scaffolds Targeting Overexpressed Cancer Cell Kinases',
                'author_name' => 'Prof. P. Leelavathi, Dr. G. Ramesh',
                'doi_number' => '10.1016/j.bmcl.2024.129881',
                'publication_date' => '2024-11-20',
                'publication_journal' => 'Bioorganic & Medicinal Chemistry Letters',
                'impact_factor' => 2.800,
            ],
            [
                'task_no' => 'T5.1',
                'publication_title' => 'Comprehensive In-Silico ADMET Profiling and Oral Bioavailability Prediction of Clinical Lead Candidates',
                'author_name' => 'Dr. V. Vijjulatha, Prof. P. Leelavathi',
                'doi_number' => '10.1002/cmdc.202400318',
                'publication_date' => '2024-08-16',
                'publication_journal' => 'ChemMedChem',
                'impact_factor' => 3.400,
            ],
        ],
        'patents' => [
            [
                'task_no' => 'T5.1',
                'patent_id' => 'PAT-OU-01',
                'patent_title' => 'Novel Heterocyclic Pyrazole-Triazole Hybrid Compounds for Kinase Inhibition',
                'inventor_name' => 'Dr. V. Vijjulatha',
                'co_inventors' => 'Prof. P. Leelavathi',
                'application_no' => '202441089102',
                'patent_no' => '',
                'country' => 'India',
                'filing_date' => '2024-04-10',
                'publication_date' => '2024-10-18',
                'grant_date' => null,
                'status' => 'Published',
                'technology_area' => 'Medicinal Chemistry & Drug Discovery',
                'abstract' => 'A novel class of synthetic chemical entities comprising a fused pyrazole-triazole pharmacophore showing high selectivity toward cancer kinases.',
            ],
            [
                'task_no' => 'T5.2',
                'patent_id' => 'PAT-OU-02',
                'patent_title' => 'In-Silico High-Throughput Screening Methodology for Kinase Binding Optimization',
                'inventor_name' => 'Dr. V. Vijjulatha',
                'co_inventors' => 'Dr. G. Ramesh',
                'application_no' => '202541018241',
                'patent_no' => '',
                'country' => 'India',
                'filing_date' => '2025-03-05',
                'publication_date' => null,
                'grant_date' => null,
                'status' => 'Filed',
                'technology_area' => 'Computational Cheminformatics',
                'abstract' => 'An automated computational pipeline coupling pharmacophore alignment, quantum-mechanical scoring, and molecular dynamics for rapid virtual screening.',
            ],
        ],
        'internships' => [
            [
                'task_no' => 'T5.1',
                'title' => 'Computer-Aided Drug Design (CADD) & Molecular Docking Training Program',
                'project_investigator' => 'Dr. V. Vijjulatha',
                'no_students_trained' => 12,
                'students_names' => 'K. Sai Krishna, M. Priyanka, R. Sandeep, S. Bhavani, V. Naveen, G. Swetha, P. Anudeep, B. Harish, K. Sravani, D. Rakesh, T. Divya, M. Vineeth',
                'no_days_trained' => 30,
                'content' => 'Protein crystal structure preparation, ligand conformational sampling, grid-based docking protocols, and binding energy calculations.',
            ],
            [
                'task_no' => 'T5.2',
                'title' => 'Synthetic Organic Chemistry and Spectroscopic Identification Fellowship',
                'project_investigator' => 'Prof. P. Leelavathi',
                'no_students_trained' => 9,
                'students_names' => 'N. Srinivas, P. Archana, K. Rajesh, M. Sushma, G. Prashanth, T. Manasa, CH. Rohit, A. Deepa, B. Kiran',
                'no_days_trained' => 25,
                'content' => 'Reflux heating, TLC monitoring, column chromatography purification, and structure assignment using 1H-NMR and LC-MS.',
            ],
            [
                'task_no' => 'T5.3',
                'title' => 'Molecular Dynamics Simulations using GROMACS & Free Energy Methods',
                'project_investigator' => 'Dr. G. Ramesh',
                'no_students_trained' => 8,
                'students_names' => 'V. Haritha, S. Mahesh, P. Lavanya, R. Karthik, K. Vinay, M. Soumya, T. Ravinder, G. Sneha',
                'no_days_trained' => 20,
                'content' => 'Force field parameter generation, system solvation, NVT/NPT equilibration, RMSD/RMSF trajectory analysis, and MMPBSA scripting.',
            ],
        ],
        'webinars' => [
            [
                'taskno' => 'T5.1',
                'title' => 'Computational Pharmacophore Mapping & Molecular Docking for Kinase Inhibitors',
                'speaker_name' => 'Dr. V. Vijjulatha',
                'affiliation' => 'Department of Chemistry, Osmania University',
                'webinar_date' => '2025-05-15 11:00:00',
                'link' => 'https://meet.google.com/ou-cadd-2025',
                'description' => 'Comprehensive webinar on 3D QSAR, pharmacophore generation, and virtual screening workflows against oncological targets.',
            ],
            [
                'taskno' => 'T5.2',
                'title' => 'In-Silico ADMET Screening & Structure-Activity Relationship (SAR)',
                'speaker_name' => 'Prof. P. Leelavathi',
                'affiliation' => 'Department of Chemistry, Osmania University',
                'webinar_date' => '2025-04-02 14:30:00',
                'link' => 'https://meet.google.com/ou-admet-2025',
                'description' => 'Mechanisms of drug metabolism, oral bioavailability optimization, and pharmacokinetic lead tuning in medicinal chemistry.',
            ],
            [
                'taskno' => 'T5.3',
                'title' => 'Structure-Guided Optimization of Novel Heterocyclic Anticancer Agents',
                'speaker_name' => 'Dr. G. Ramesh',
                'affiliation' => 'Department of Chemistry, Osmania University',
                'webinar_date' => '2025-02-18 10:30:00',
                'link' => 'https://meet.google.com/ou-heterocycle-2025',
                'description' => 'Synthetic methodologies, NMR structural elucidation, and kinase inhibition profiles of heterocyclic compounds.',
            ],
        ],
        'conferences' => [
            [
                'taskno' => 'T5.1',
                'title' => 'Annual Conference on Computational Pharmacophore Modeling & AI in Drug Discovery',
                'conf_date' => '2025-07-28',
                'organisers' => 'Department of Chemistry, Osmania University, Hyderabad',
                'institute' => 'Osmania University',
                'investigator' => 'Dr. V. Vijjulatha & Prof. P. Leelavathi',
                'content' => 'Two-day national conference hosting 160 medicinal chemists and bioinformaticians discussing machine learning applications in lead drug candidate discovery.',
            ],
            [
                'taskno' => 'T5.2',
                'title' => 'National Seminar on Frontier Developments in Heterocyclic Medicinal Chemistry',
                'conf_date' => '2024-12-10',
                'organisers' => 'University College of Science, Osmania University',
                'institute' => 'Osmania University',
                'investigator' => 'Prof. P. Leelavathi',
                'content' => 'National gathering presenting innovative synthetic organic routes and therapeutic bioactivities of nitrogen and sulfur containing heterocycles.',
            ],
        ],
    ],

    'svu' => [
        'name' => 'Sri Venkateswara University',
        'progress' => [
            [
                'project_title' => 'Phytochemical Profiling and Antioxidant Activity of Endemic Medicinal Plants',
                'pi_name' => 'Prof. Balaji Meriga',
                'co_pi_name' => 'Dr. G. Sarma',
                'task_no' => 'T6.1',
                'work_package_no' => 'WP1',
                'approved_objects' => 'Extract, identify, and quantify polyphenolic bioactive compounds from Seshachalam endemic flora.',
                'methodology' => 'Soxhlet extraction, HPLC-DAD fingerprinting, DPPH/ABTS radical scavenging assays, and lipid peroxidation inhibition.',
                'summary_progress' => 'Isolated 12 bioactive flavonoid fractions; demonstrated significant IC50 of 8.4 ug/mL against free radicals.',
                'interns_trained_count' => 8,
            ],
            [
                'project_title' => 'Development of Smart Nano Biosensors for Rapid Healthcare Diagnostics',
                'pi_name' => 'Prof. Tata Narasinga Rao',
                'co_pi_name' => 'Prof. Balaji Meriga',
                'task_no' => 'T6.2',
                'work_package_no' => 'WP2',
                'approved_objects' => 'Fabricate electrochemical nano-biosensor strips for rapid point-of-care cardiac troponin detection.',
                'methodology' => 'Screen-printed carbon electrodes modified with gold-graphene nanocomposites and antibody immobilization.',
                'summary_progress' => 'Achieved wide linear dynamic range (0.01 to 50 ng/mL) with rapid response time of under 3 minutes.',
                'interns_trained_count' => 7,
            ],
            [
                'project_title' => 'Main Group Materials for Health, Energy, and Environmental Remediation',
                'pi_name' => 'Dr. G. Sarma',
                'co_pi_name' => 'Prof. Tata Narasinga Rao',
                'task_no' => 'T6.3',
                'work_package_no' => 'WP3',
                'approved_objects' => 'Synthesize main group metal complexes for catalytic degradation of toxic industrial effluents.',
                'methodology' => 'Inert-atmosphere Schlenk line synthesis, single crystal X-ray diffraction, and UV-vis photocatalytic monitoring.',
                'summary_progress' => 'Synthesized 6 novel aluminum and boron complexes displaying 96% photocatalytic dye degradation.',
                'interns_trained_count' => 6,
            ],
            [
                'project_title' => 'Evaluation of Protective Phytotherapeutics Against Heavy Metal-Induced Nephrotoxicity',
                'pi_name' => 'Prof. Balaji Meriga',
                'co_pi_name' => 'Dr. G. Sarma',
                'task_no' => 'T6.4',
                'work_package_no' => 'WP3',
                'approved_objects' => 'Investigate in-vivo cytoprotective effects of standardized plant extracts in heavy metal-exposed animal models.',
                'methodology' => 'Serum creatinine/BUN biomarker profiling, renal histopathology, and oxidative enzyme quantification.',
                'summary_progress' => 'Demonstrated 70% restoration of superoxide dismutase activity and marked attenuation of tubular necrosis.',
                'interns_trained_count' => 5,
            ],
        ],
        'publications' => [
            [
                'task_no' => 'T6.1',
                'publication_title' => 'Phytochemical Fingerprinting and Free Radical Scavenging Mechanisms of Flavonoid Glycosides from Seshachalam Biosphere Reserve Flora',
                'author_name' => 'Prof. Balaji Meriga, Dr. G. Sarma, et al.',
                'doi_number' => '10.1016/j.phytochem.2025.114120',
                'publication_date' => '2025-06-28',
                'publication_journal' => 'Phytochemistry',
                'impact_factor' => 4.000,
            ],
            [
                'task_no' => 'T6.2',
                'publication_title' => 'A High-Sensitivity Electrochemical Immunosensor for Cardiac Troponin-I Using Gold Nanoparticle-Decorated Graphene Sheets',
                'author_name' => 'Prof. Tata Narasinga Rao, Prof. Balaji Meriga',
                'doi_number' => '10.1016/j.bios.2025.116280',
                'publication_date' => '2025-04-18',
                'publication_journal' => 'Biosensors and Bioelectronics',
                'impact_factor' => 12.600,
            ],
            [
                'task_no' => 'T6.3',
                'publication_title' => 'Synthesis, Structural Elucidation, and Catalytic Properties of Novel Main Group Organometallic Catalysts',
                'author_name' => 'Dr. G. Sarma, Prof. Tata Narasinga Rao',
                'doi_number' => '10.1021/acs.inorgchem.4c03890',
                'publication_date' => '2024-11-05',
                'publication_journal' => 'Inorganic Chemistry (ACS)',
                'impact_factor' => 4.600,
            ],
        ],
        'patents' => [
            [
                'task_no' => 'T6.2',
                'patent_id' => 'PAT-SVU-01',
                'patent_title' => 'A Disposable Screen-Printed Nano-Electrode Biosensor for Diagnostic Biomarker Quantification',
                'inventor_name' => 'Prof. Tata Narasinga Rao',
                'co_inventors' => 'Prof. Balaji Meriga',
                'application_no' => '202441091873',
                'patent_no' => '',
                'country' => 'India',
                'filing_date' => '2024-05-22',
                'publication_date' => '2024-11-30',
                'grant_date' => null,
                'status' => 'Published',
                'technology_area' => 'Point-of-Care Biosensors & Nanotechnology',
                'abstract' => 'An electrochemical test strip functionalized with graphene-metal nanocomposites for label-free picogram detection of clinical biomarkers.',
            ],
            [
                'task_no' => 'T6.1',
                'patent_id' => 'PAT-SVU-02',
                'patent_title' => 'Novel Phytochemical Formulation from Endemic Plants for Cellular Oxidative Protection',
                'inventor_name' => 'Prof. Balaji Meriga',
                'co_inventors' => 'Dr. G. Sarma',
                'application_no' => '202541016334',
                'patent_no' => '',
                'country' => 'India',
                'filing_date' => '2025-02-25',
                'publication_date' => null,
                'grant_date' => null,
                'status' => 'Filed',
                'technology_area' => 'Phytomedicine & Nutraceuticals',
                'abstract' => 'A synergistic antioxidant formulation comprising polyphenolic fractions demonstrating high cellular bioavailability and mitochondrial preservation.',
            ],
        ],
        'internships' => [
            [
                'task_no' => 'T6.1',
                'title' => 'Phytochemical Analysis and Chromatographic Techniques Fellowship',
                'project_investigator' => 'Prof. Balaji Meriga',
                'no_students_trained' => 10,
                'students_names' => 'P. Murali, K. Haritha, S. Vinod, M. Rajeshwari, G. Ravi Kumar, B. Lavanya, T. Suresh, V. Geetha, K. Naveen, P. Anitha',
                'no_days_trained' => 30,
                'content' => 'Solvent extraction protocols, rotary evaporator concentration, HPLC column packing, and chromatographic peak integration.',
            ],
            [
                'task_no' => 'T6.2',
                'title' => 'Electrochemical Biosensor Fabrication & Nanomaterial Modification Workshop',
                'project_investigator' => 'Prof. Tata Narasinga Rao',
                'no_students_trained' => 9,
                'students_names' => 'N. Bhaskar, R. Madhavi, S. Kiran, K. Pavani, M. Ramesh, D. Swarna, V. Mahesh, B. Pushpa, T. Srinivas',
                'no_days_trained' => 25,
                'content' => 'Screen printing of carbon electrodes, cyclic voltammetry (CV) characterization, electrochemical impedance spectroscopy (EIS), and antibody conjugation.',
            ],
            [
                'task_no' => 'T6.3',
                'title' => 'Organometallic Synthesis and Spectroscopic Characterization Internship',
                'project_investigator' => 'Dr. G. Sarma',
                'no_students_trained' => 7,
                'students_names' => 'C. Prasad, T. Sravanthi, K. Ramana, P. Sireesha, M. Naresh, S. Hema, G. Chandrasekhar',
                'no_days_trained' => 21,
                'content' => 'Vacuum line handling, inert-gas glove box manipulations, NMR sample preparation, and spectrophotometric absorbance monitoring.',
            ],
            [
                'task_no' => 'T6.4',
                'title' => 'Biochemical Assay Validation & Toxicological Animal Model Training',
                'project_investigator' => 'Prof. Balaji Meriga',
                'no_students_trained' => 8,
                'students_names' => 'Y. Subba Rao, K. Sujatha, P. Venkatesh, B. Manjula, M. Prakash, S. Shanti, R. Gopal, T. Deepthi',
                'no_days_trained' => 15,
                'content' => 'Organ homogenization, spectrophotometric enzyme kinetic determinations (SOD, catalase, GSH), and tissue microtome sectioning.',
            ],
        ],
        'webinars' => [
            [
                'taskno' => 'T6.1',
                'title' => 'Webinar on Smart Nano Biosensors for Rapid Healthcare Diagnostics',
                'speaker_name' => 'Prof. Tata Narasinga Rao (Keynote Speaker)',
                'affiliation' => 'International Advanced Research Centre for Powder Metallurgy (ARCI) & SVU',
                'webinar_date' => '2025-05-12 10:30:00',
                'link' => 'https://meet.google.com/svu-biosensors-2025',
                'description' => 'Principles of nanomaterial-modified electrochemical electrodes, point-of-care test design, and translation to commercial medical devices.',
            ],
            [
                'taskno' => 'T6.2',
                'title' => 'Phytochemical Profiling and Antioxidant Activity of Endemic Medicinal Plants',
                'speaker_name' => 'Prof. Balaji Meriga',
                'affiliation' => 'Department of Biochemistry, Sri Venkateswara University',
                'webinar_date' => '2025-04-10 14:00:00',
                'link' => 'https://meet.google.com/svu-phytochem-2025',
                'description' => 'Biochemical pathways of reactive oxygen species mitigation by endemic plant flavonoid compounds.',
            ],
            [
                'taskno' => 'T6.3',
                'title' => 'Main Group Materials for Health, Energy, and Environmental Remediation',
                'speaker_name' => 'Dr. G. Sarma',
                'affiliation' => 'Department of Chemistry, Sri Venkateswara University',
                'webinar_date' => '2025-02-15 11:30:00',
                'link' => 'https://meet.google.com/svu-maingroup-2025',
                'description' => 'Synthesis of non-toxic main group complexes for green energy catalysis and environmental wastewater remediation.',
            ],
        ],
        'conferences' => [
            [
                'taskno' => 'T6.1',
                'title' => 'National Conference on Nano-Biosensors & Translational Point-of-Care Diagnostics',
                'conf_date' => '2025-08-20',
                'organisers' => 'Department of Physics & Biochemistry, Sri Venkateswara University, Tirupati',
                'institute' => 'Sri Venkateswara University',
                'investigator' => 'Prof. Tata Narasinga Rao & Prof. Balaji Meriga',
                'content' => 'Two-day national conference convening experts in nanomaterials, clinical pathology, and bioengineering to address affordable diagnostic devices.',
            ],
            [
                'taskno' => 'T6.2',
                'title' => 'National Seminar on Medicinal Plants of Eastern Ghats: Conservation & Therapeutic Potential',
                'conf_date' => '2024-11-25',
                'organisers' => 'Department of Biochemistry, Sri Venkateswara University',
                'institute' => 'Sri Venkateswara University',
                'investigator' => 'Prof. Balaji Meriga',
                'content' => 'Conference addressing ecological conservation, phytopharmacology, and ethnobotanical validation of medicinal species from Eastern Ghats.',
            ],
        ],
    ],

    'yvu' => [
        'name' => 'Yogi Vemana University',
        'progress' => [
            [
                'project_title' => 'Green Synthesis of Silver Nanoparticles using Plant Extracts for Anti-Microbial Coatings',
                'pi_name' => 'Dr. G. Sarma',
                'co_pi_name' => 'Prof. L. Dakshayani',
                'task_no' => 'T7.1',
                'work_package_no' => 'WP1',
                'approved_objects' => 'Synthesize eco-friendly silver nanoparticles using leaf aqueous extracts and evaluate antibacterial properties.',
                'methodology' => 'Green reduction synthesis, UV-visible SPR peak monitoring at 420nm, DLS particle size analysis, and agar well diffusion.',
                'summary_progress' => 'Synthesized monodisperse 22nm silver nanoparticles; demonstrated 18mm zone of inhibition against multi-drug resistant E. coli.',
                'interns_trained_count' => 6,
            ],
            [
                'project_title' => 'Flow Cytometry Training & Analytical Instrumentation Collaborative Center',
                'pi_name' => 'Prof. L. Dakshayani',
                'co_pi_name' => 'Dr. G. Sarma',
                'task_no' => 'T7.2',
                'work_package_no' => 'WP2',
                'approved_objects' => 'Establish regional node for flow cytometry sample preparation and collaborative cell cycle analysis.',
                'methodology' => 'Propidium iodide DNA staining, cell cycle phase deconvolution, and collaborative cross-validation with Hub at UoH.',
                'summary_progress' => 'Trained 45 regional postgraduate students; analyzed cell cycle profiles of 60 botanical extract-treated cancer lines.',
                'interns_trained_count' => 8,
            ],
        ],
        'publications' => [
            [
                'task_no' => 'T7.1',
                'publication_title' => 'Phyto-Assisted Eco-Friendly Synthesis of Silver Nanoparticles: Optimization, Characterization, and Enhanced Antibacterial Dynamics',
                'author_name' => 'Dr. G. Sarma, Prof. L. Dakshayani, et al.',
                'doi_number' => '10.1016/j.jphotobiol.2025.112940',
                'publication_date' => '2025-05-30',
                'publication_journal' => 'Journal of Photochemistry and Photobiology B: Biology',
                'impact_factor' => 6.200,
            ],
            [
                'task_no' => 'T7.2',
                'publication_title' => 'Collaborative Spoke-Hub Pipeline for High-Resolution Cell Cycle Analysis of Botanical Therapeutics',
                'author_name' => 'Prof. L. Dakshayani, Dr. G. Sarma, Prof. K. Anand',
                'doi_number' => '10.1007/s12033-024-01290-x',
                'publication_date' => '2024-10-15',
                'publication_journal' => 'Molecular Biotechnology',
                'impact_factor' => 2.800,
            ],
        ],
        'patents' => [
            [
                'task_no' => 'T7.1',
                'patent_id' => 'PAT-YVU-01',
                'patent_title' => 'Process for Phyto-Synthesizing Highly Stable Silver Nanoparticles with Enhanced Antibacterial Activity',
                'inventor_name' => 'Dr. G. Sarma',
                'co_inventors' => 'Prof. L. Dakshayani',
                'application_no' => '202441092401',
                'patent_no' => '',
                'country' => 'India',
                'filing_date' => '2024-05-28',
                'publication_date' => '2024-12-05',
                'grant_date' => null,
                'status' => 'Published',
                'technology_area' => 'Green Nanotechnology & Antimicrobial Agents',
                'abstract' => 'A single-step eco-friendly process utilizing leaf aqueous extract as simultaneous reducing and capping agent for producing oxidation-resistant silver nanoparticles.',
            ],
        ],
        'internships' => [
            [
                'task_no' => 'T7.1',
                'title' => 'Research Training Program: YVU-UoH Collaborative Analytical Instrumentation',
                'project_investigator' => 'Prof. L. Dakshayani',
                'no_students_trained' => 12,
                'students_names' => 'B. Venkat, K. Sujatha, S. Rafi, M. Anitha, P. Sudhakar, D. Sravanthi, T. Ravi, G. Nirmala, K. Madhusudhan, R. Prabhavathi, V. Naresh, A. Divya',
                'no_days_trained' => 21,
                'content' => 'UV-Vis spectrophotometer calibration, dynamic light scattering (DLS) size measurement, and bacterial colony counting.',
            ],
            [
                'task_no' => 'T7.2',
                'title' => 'Workshop on Flow Cytometry: Sample Preparation and Data Acquisition',
                'project_investigator' => 'Dr. G. Sarma',
                'no_students_trained' => 10,
                'students_names' => 'N. Harish, P. Chandrakala, S. Srinivasulu, M. Kavitha, G. Prasad, B. Sailaja, K. Sreedhar, T. Lakshmi, D. Ramesh, C. Pushpalatha',
                'no_days_trained' => 15,
                'content' => 'Cell fixation protocols, RNase treatment, propidium iodide staining, and fluorescence intensity histogram gating.',
            ],
        ],
        'webinars' => [
            [
                'taskno' => 'T7.1',
                'title' => 'Green Synthesis of Silver Nanoparticles for Anti-Microbial Coatings',
                'speaker_name' => 'Dr. G. Sarma',
                'affiliation' => 'Department of Chemistry, Yogi Vemana University',
                'webinar_date' => '2025-05-19 11:30:00',
                'link' => 'https://meet.google.com/yvu-greensynth-2025',
                'description' => 'Mechanisms of biological reduction, particle capping dynamics, and surface coating antimicrobial applications.',
            ],
            [
                'taskno' => 'T7.2',
                'title' => 'Research Training Program: YVU-UoH-ANRF-PAIR Collaborative Initiative',
                'speaker_name' => 'ANRF-PAIR Team',
                'affiliation' => 'Yogi Vemana University & University of Hyderabad',
                'webinar_date' => '2025-03-10 14:00:00',
                'link' => 'https://meet.google.com/yvu-training-2025',
                'description' => 'Orientation webinar showcasing central instrumentation capabilities and spoke student research opportunities.',
            ],
        ],
        'conferences' => [
            [
                'taskno' => 'T7.1',
                'title' => 'Workshop on Flow Cytometry: Principles, Applications, and Hands-on Training',
                'conf_date' => '2025-06-18',
                'organisers' => 'ANRF-PAIR Project in association with BD Bioscience, India at Yogi Vemana University',
                'institute' => 'Yogi Vemana University',
                'investigator' => 'Prof. L. Dakshayani & Dr. G. Sarma',
                'content' => 'Joint multi-institutional training symposium providing hands-on biomedical research exposure in flow cytometric applications for faculty and scholars.',
            ],
        ],
    ],
];

echo "Beginning distinct migration across all 7 universities...\n";

foreach ($allData as $pfx => $data) {
    echo "Processing {$data['name']} ($pfx)...\n";

    // 1. Progress Reports
    $progTbl = "{$pfx}_progress_reports";
    $pdo->exec("DELETE FROM `$progTbl`");
    $stmt = $pdo->prepare("
        INSERT INTO `$progTbl`
        (project_title, pi_name, co_pi_name, task_no, work_package_no, approved_objects, methodology, summary_progress, interns_trained_count, created_at)
        VALUES
        (:title, :pi, :copi, :task, :wp, :obj, :meth, :prog, :interns, NOW())
    ");
    foreach ($data['progress'] as $item) {
        $stmt->execute([
            ':title' => $item['project_title'],
            ':pi' => $item['pi_name'],
            ':copi' => $item['co_pi_name'],
            ':task' => $item['task_no'],
            ':wp' => $item['work_package_no'],
            ':obj' => $item['approved_objects'],
            ':meth' => $item['methodology'],
            ':prog' => $item['summary_progress'],
            ':interns' => $item['interns_trained_count'],
        ]);
    }

    // 2. Publications
    $pubTbl = "{$pfx}_publications";
    $pdo->exec("DELETE FROM `$pubTbl`");
    $stmt = $pdo->prepare("
        INSERT INTO `$pubTbl`
        (task_no, publication_title, author_name, doi_number, publication_date, publication_journal, impact_factor, created_at)
        VALUES
        (:task, :title, :author, :doi, :pdate, :journal, :ifactor, NOW())
    ");
    foreach ($data['publications'] as $item) {
        $stmt->execute([
            ':task' => $item['task_no'],
            ':title' => $item['publication_title'],
            ':author' => $item['author_name'],
            ':doi' => $item['doi_number'],
            ':pdate' => $item['publication_date'],
            ':journal' => $item['publication_journal'],
            ':ifactor' => $item['impact_factor'],
        ]);
    }

    // 3. Patents
    $patTbl = "{$pfx}_patent";
    $pdo->exec("DELETE FROM `$patTbl`");
    $stmt = $pdo->prepare("
        INSERT INTO `$patTbl`
        (task_no, patent_id, patent_title, inventor_name, co_inventors, application_no, patent_no, country, filing_date, publication_date, grant_date, status, technology_area, abstract, created_at)
        VALUES
        (:task, :pid, :title, :inv, :coinv, :appno, :patno, :country, :fdate, :pdate, :gdate, :status, :tech, :abs, NOW())
    ");
    foreach ($data['patents'] as $item) {
        $stmt->execute([
            ':task' => $item['task_no'],
            ':pid' => $item['patent_id'],
            ':title' => $item['patent_title'],
            ':inv' => $item['inventor_name'],
            ':coinv' => $item['co_inventors'],
            ':appno' => $item['application_no'],
            ':patno' => $item['patent_no'] ?: null,
            ':country' => $item['country'],
            ':fdate' => $item['filing_date'],
            ':pdate' => $item['publication_date'] ?: null,
            ':gdate' => $item['grant_date'] ?: null,
            ':status' => $item['status'],
            ':tech' => $item['technology_area'],
            ':abs' => $item['abstract'],
        ]);
    }

    // 4. Internships
    $intTbl = "{$pfx}_internships";
    $pdo->exec("DELETE FROM `$intTbl`");
    $stmt = $pdo->prepare("
        INSERT INTO `$intTbl`
        (task_no, title, project_investigator, no_students_trained, students_names, no_days_trained, content, created_at)
        VALUES
        (:task, :title, :pi, :students, :snames, :days, :content, NOW())
    ");
    foreach ($data['internships'] as $item) {
        $stmt->execute([
            ':task' => $item['task_no'],
            ':title' => $item['title'],
            ':pi' => $item['project_investigator'],
            ':students' => $item['no_students_trained'],
            ':snames' => $item['students_names'],
            ':days' => $item['no_days_trained'],
            ':content' => $item['content'],
        ]);
    }

    // 5. Webinars
    $webTbl = "{$pfx}_webinars";
    $pdo->exec("DELETE FROM `$webTbl`");
    $stmt = $pdo->prepare("
        INSERT INTO `$webTbl`
        (taskno, title, speaker_name, affiliation, webinar_date, link, description, publish_status, approval_status, created_at)
        VALUES
        (:task, :title, :speaker, :affil, :wdate, :link, :desc, 1, 'Approved', NOW())
    ");
    foreach ($data['webinars'] as $item) {
        $stmt->execute([
            ':task' => $item['taskno'],
            ':title' => $item['title'],
            ':speaker' => $item['speaker_name'],
            ':affil' => $item['affiliation'],
            ':wdate' => $item['webinar_date'],
            ':link' => $item['link'],
            ':desc' => $item['description'],
        ]);
    }

    // 6. Conferences
    $confTbl = "{$pfx}_conferences";
    $pdo->exec("DELETE FROM `$confTbl`");
    $stmt = $pdo->prepare("
        INSERT INTO `$confTbl`
        (taskno, title, conf_date, organisers, institute, investigator, content, publish_status, approval_status, created_at)
        VALUES
        (:task, :title, :cdate, :org, :inst, :inv, :content, 1, 'Approved', NOW())
    ");
    foreach ($data['conferences'] as $item) {
        $stmt->execute([
            ':task' => $item['taskno'],
            ':title' => $item['title'],
            ':cdate' => $item['conf_date'],
            ':org' => $item['organisers'],
            ':inst' => $item['institute'],
            ':inv' => $item['investigator'],
            ':content' => $item['content'],
        ]);
    }

    echo "  -> Completed {$pfx}\n";
}

echo "All migrations completed successfully!\n";
